### PR TITLE
Add read lengths to lanes billing report

### PR DESCRIPTION
**Pull request by callunity**

### CODE REVIEW

**Comment by sqwci** [comment]
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [LanesBillingReport.java#L216](https://github.com/oicr-gsi/pinery-reports/blob/7345ade0bae50ae533cae23352226d073cbba5e4/src/main/java/ca/on/oicr/pineryreports/reports/impl/LanesBillingReport.java#L216): Refactor this method to reduce its Cognitive Complexity from 39 to the 15 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [LanesBillingReport.java#L259](https://github.com/oicr-gsi/pinery-reports/blob/7345ade0bae50ae533cae23352226d073cbba5e4/src/main/java/ca/on/oicr/pineryreports/reports/impl/LanesBillingReport.java#L259): Extract this nested ternary operation into an independent statement. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3358)
1. ![MINOR][MINOR] [LanesBillingReport.java#L224](https://github.com/oicr-gsi/pinery-reports/blob/7345ade0bae50ae533cae23352226d073cbba5e4/src/main/java/ca/on/oicr/pineryreports/reports/impl/LanesBillingReport.java#L224): Reduce the total number of break and continue statements in this loop to use at most one. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS135)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by sqwci** [comment]
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [LanesBillingReport.java#L216](https://github.com/oicr-gsi/pinery-reports/blob/c97718287862bab70a58b652b3d47e02965ec5af/src/main/java/ca/on/oicr/pineryreports/reports/impl/LanesBillingReport.java#L216): Refactor this method to reduce its Cognitive Complexity from 39 to the 15 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [LanesBillingReport.java#L259](https://github.com/oicr-gsi/pinery-reports/blob/c97718287862bab70a58b652b3d47e02965ec5af/src/main/java/ca/on/oicr/pineryreports/reports/impl/LanesBillingReport.java#L259): Extract this nested ternary operation into an independent statement. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3358)
1. ![MINOR][MINOR] [LanesBillingReport.java#L224](https://github.com/oicr-gsi/pinery-reports/blob/c97718287862bab70a58b652b3d47e02965ec5af/src/main/java/ca/on/oicr/pineryreports/reports/impl/LanesBillingReport.java#L224): Reduce the total number of break and continue statements in this loop to use at most one. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS135)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by callunity** [comment]
Documentation updated, thanks for the review!

**Comment by sqwci** [comment]
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [LanesBillingReport.java#L216](https://github.com/oicr-gsi/pinery-reports/blob/5a5004f67a6d48a9128b98bce31bb42997177b0e/src/main/java/ca/on/oicr/pineryreports/reports/impl/LanesBillingReport.java#L216): Refactor this method to reduce its Cognitive Complexity from 39 to the 15 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [LanesBillingReport.java#L259](https://github.com/oicr-gsi/pinery-reports/blob/5a5004f67a6d48a9128b98bce31bb42997177b0e/src/main/java/ca/on/oicr/pineryreports/reports/impl/LanesBillingReport.java#L259): Extract this nested ternary operation into an independent statement. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3358)
1. ![MINOR][MINOR] [LanesBillingReport.java#L224](https://github.com/oicr-gsi/pinery-reports/blob/5a5004f67a6d48a9128b98bce31bb42997177b0e/src/main/java/ca/on/oicr/pineryreports/reports/impl/LanesBillingReport.java#L224): Reduce the total number of break and continue statements in this loop to use at most one. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS135)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by sqwci** [comment]
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [LanesBillingReport.java#L216](https://github.com/oicr-gsi/pinery-reports/blob/6e847de138a8df84844c21a0d0ed640223cc2bd1/src/main/java/ca/on/oicr/pineryreports/reports/impl/LanesBillingReport.java#L216): Refactor this method to reduce its Cognitive Complexity from 39 to the 15 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [LanesBillingReport.java#L259](https://github.com/oicr-gsi/pinery-reports/blob/6e847de138a8df84844c21a0d0ed640223cc2bd1/src/main/java/ca/on/oicr/pineryreports/reports/impl/LanesBillingReport.java#L259): Extract this nested ternary operation into an independent statement. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3358)
1. ![MINOR][MINOR] [LanesBillingReport.java#L224](https://github.com/oicr-gsi/pinery-reports/blob/6e847de138a8df84844c21a0d0ed640223cc2bd1/src/main/java/ca/on/oicr/pineryreports/reports/impl/LanesBillingReport.java#L224): Reduce the total number of break and continue statements in this loop to use at most one. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS135)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
